tools:
  # other binary versions inherited from go-make

  # used for linting
  - name: golangci-lint
    version:
      want: v1.64.8
    method: github-release
    with:
      repo: golangci/golangci-lint
